### ISSUE TITLE
fwa_watershed call returning error

### ISSUE THREAD

**Issue by oconnorbryce** [poissonconsulting/fwapgr#12]
Attempting to extract sf of Parsnip River following code provided in Get Started vignette. I was able to successfully extract sf for Yakoun and the Chilcotin Rivers as a check. 

running:

wshed <- fwapgr::fwa_watershed(blue_line_key)

returns:

Error: API request failed [500]: column reference "geom" is ambiguous.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/chk_error>
API request failed [500]: column reference "geom" is ambiguous.
Backtrace:
 1. fwapgr::fwa_watershed(blue_line_key)
 2. fwapgr:::fwa_api(path, query)
 3. fwapgr:::chk_response_status(resp)
 4. chk::abort_chk(glue("API request failed [{status_code(x)}]: {msg}"))
 5. chk::err(..., n = n, tidy = tidy, .subclass = "chk_error")
 6. rlang::exec(abort, msg, .subclass = .subclass, !!!args[named])
Run `rlang::last_trace()` to see the full context.

Suggestions?

**Comment by smnorris** [comment]
Definitely an issue on my end, should be an easy fix.

**Comment by smnorris** [comment]
Keep in mind that there is also the layer `fwa_named_watersheds_poly`. It should return an entire named watershed much more quickly than the `watershed` function. The watershed function is designed for more for creating a watershed at an arbitrary point along a stream - where there is not already a pre-aggregated feature in the database.

**Comment by smnorris** [comment]
Fixed in the API, but definitely consider using `fwa_named_watersheds_poly` any time you are not providing the watershed function with a `downstream_route_measure`. 

I think that would be something like this:
`fwapgr::fwa_feature("fwa_named_watersheds_poly", filter = "gnis_name = 'Parsnip River'")`

**Comment by sebdalgarno** [comment]
Thanks  @smnorris 
I'm now getting a 502 Bad Gateway error from:
```
wshed <- fwa_watershed(359567332)
```

I assume this might be some kind of timeout issue?

@oconnorbryce, as Simon suggested, you could use this instead:
```
parsnip <- fwa_feature("fwa_named_watersheds_poly", filter = "gnis_name = 'Parsnip River'")
```

**Comment by smnorris** [comment]
Yes, it looks like something is timing out, I'll look into it. 
You're requesting Parsnip upstream of `downstream_route_measure = 0`. This is inside a lake - a special case that I thought I'd fixed.

Use named watersheds or watershed groups for now.

**Comment by smnorris** [comment]
I should note that this special case is going to give you something much different that what you might expect. Because the measure 0 feature of Parsnip River is in Williston Lake, the `watershed` query is going to return everything that drains into that lake. So you'll get everything upstream of WAC Bennet Dam... This is behaviour requested by the client - if you want the area upstream of a lake, include everything that drains into the lake. 

Ask for the watershed at >=500m up the Parsnip (where the stream line is no longer in the lake) and all will work fine.

**Comment by sebdalgarno** [comment]
ok thanks for the clarification @smnorris ... I'm going to close this issue for now and update the vignette at some point to clarify the watersheds function

**Comment by smnorris** [comment]
👍 documentation of the watershed and nearest stream functions is on my to-do list

**Comment by sebdalgarno** [comment]
actually I think I'll add a wrapper for the nearest stream function and build an example combining those two...

**Comment by oconnorbryce** [comment]
Getting similar 502 Bad Gateway from fwa_watershed, but was able to get the streams using

    parsnip <- fwa_feature("fwa_named_watersheds_poly", filter = "gnis_name = 'Parsnip River'")

Thanks for the help

**Comment by smnorris** [comment]
Along with some documentation, to make things clearer I might rename the watershed function to `fwa_watershed_at_measure` or similar and make `downstream_route_measure` a required parameter.

**Comment by sebdalgarno** [comment]
yes feel free to do so. Actually can you just explain briefly what downstream_route_measure does? I'm not sure i fully understand

**Comment by smnorris** [comment]
`downstream_route_measure` column is the distance to the mouth of the stream in m. The 'stream' being a distinct `blue_line_key` / `fwa_watershed_code`
User guide - https://www2.gov.bc.ca/assets/gov/data/geobc/using_freshwater_atlas_data.pdf
Lots more docs - ftp://ftp.geobc.gov.bc.ca/sections/outgoing/bmgs/FWA_Public/Documents

**Comment by smnorris** [comment]
Sorry, that isn't the user guide I was looking for, the one on the ftp site is much more useful. ftp://ftp.geobc.gov.bc.ca/sections/outgoing/bmgs/FWA_Public/Documents/Freshwater_Atlas_User_Guide_Sept2009.pdf
Especially when combined with the spec
https://www2.gov.bc.ca/assets/gov/data/geographic/topography/fwa/fwa_sde_warehouse_model_specs.pdf

I don't add much to what is documented in that spec.
