### ISSUE TITLE
update to new API

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/fwapgr#13]
from Simon:
New API is still a bit buggy but is up and running:
https://hillcrestgeo.ca/fwapg/api.html
https://hillcrestgeo.ca/fwapg/
https://www.hillcrestgeo.ca/fwapg/collections/whse_basemapping.fwa_glaciers_poly/items.html

I'll start adding functions next week - but the v1 API will be available for a while yet, no rush to switch over.

**Comment by smnorris** [comment]
`fwa_watershed_at_point` is live https://www.hillcrestgeo.ca/fwapg/functions.html

**Comment by smnorris** [comment]
Not quite there - function shows up and name is fixed... but the request isn't getting through `Jul 16 15:08:09 ubuntu1604sfo1 pg_featureserv[9206]: time="2020-07-16T15:08:09-07:00" level=debug msg="Request processing error: Unable to read data from: fwa_watershed_at_measure (404)\n"`

**Comment by smnorris** [comment]
ok, it seems to be working now: https://www.hillcrestgeo.ca/fwapg/functions/fwa_watershed_at_measure/items.html?blkey=354153927&meas=100

I'm sure there will be edge cases where it is quirky or doesn't work at all - let me know over in the `fwapg` issues.

**Comment by smnorris** [comment]
FWA_NearestStream function is now live and function names have been standardized to CamelCase (above link no longer works)

https://www.hillcrestgeo.ca/fwapg/functions.html

So.... 

find the closest stream:
https://www.hillcrestgeo.ca/fwapg/functions/fwa_neareststream/items.json?x=-123.5708&y=48.6489&srid=4326

get the watershed from the blue_line_key and measure returned:
https://www.hillcrestgeo.ca/fwapg/functions/fwa_watershedatmeasure/items.json?blkey=354153555&meas=113.84795

**Comment by smnorris** [comment]
New API is no longer buggy - FWA tables with `ltree` type columns now work fine: https://hillcrestgeo.ca/fwapg/

Main pg_featureserv doesn't support this type yet
https://github.com/CrunchyData/pg_featureserv/issues/51

But I re-built with this PR and all works nicely.
https://github.com/CrunchyData/pg_featureserv/pull/52

**Comment by sebdalgarno** [comment]
done - thanks @smnorris !

**Comment by smnorris** [comment]
Is it safe to take down www.hillcrestgeo.ca/fwa ?

**Comment by sebdalgarno** [comment]
yes you can take it down...we will deprecate current functions using it
