### ISSUE TITLE
Add transform arg?

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/fwapgr#16]

**Comment by sebdalgarno** [comment]
not quite sure how this works in the API yet and what is the expected input
from API: "Geometry transformation function pipeline to apply"

**Comment by sebdalgarno** [comment]
currently not supported in R client but available as a query parameter in API

**Comment by joethorley** [comment]
see issue #24

**Comment by sebdalgarno** [comment]
@smnorris any idea why the following (with transform argument) doesn't work?
`https://hillcrestgeo.ca/fwapg/collections/whse_basemapping.fwa_stream_networks_sp/items.json?gnis_name=Chilliwack%20Creek&limit=10000&offset=0&transform=ST_Envelope`

but this does work (without transform argument):
`https://hillcrestgeo.ca/fwapg/collections/whse_basemapping.fwa_stream_networks_sp/items.json?gnis_name=Chilliwack%20Creek&limit=10000&offset=0`

**Comment by smnorris** [comment]
I haven't enabled it - I didn't notice the functionality till Martin mentioned it here https://github.com/poissonconsulting/fwapgr/issues/18#issuecomment-684163207

Can turn it on if you want. I'm not clear on what it does yet either.

**Comment by smnorris** [comment]
Ok, I get it - you want to know the extent of the features, not the features themselves. I can just enable all of the transforms

**Comment by sebdalgarno** [comment]
yes please turn it on! I think it could be really useful for us

**Comment by smnorris** [comment]
Done - this returns a result now: 
https://hillcrestgeo.ca/fwapg/collections/whse_basemapping.fwa_stream_networks_sp/items.json?gnis_name=Chilliwack%20Creek&limit=10000&offset=0

I am not so sure it is what you want for your bbox function, it looks like the envelope for every feature

**Comment by smnorris** [comment]
I am thinking you want https://postgis.net/docs/ST_Extent.html - but that isn't one of the tranform funcs. Without looking into the pg_featureserv code I'm not sure it could be either, since it is an aggregation it may not be as simple to wrap the features.

**Comment by sebdalgarno** [comment]
OK great thanks @smnorris. Getting bbox with transform may not be an option for now then...but should be able to make use of some of the other transform funcs
