### ISSUE TITLE
fwa_neareststream name change

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/fwapgr#23]
see here in fwapg: https://github.com/smnorris/fwapg/issues/27
change to fwa_indexpoint

**Comment by sebdalgarno** [comment]
nearest_stream still works as not deprecated
@smnorris are you planning on deprecating fwa_neareststream, i.e. do I need to switch over to fwa_indexpoint

**Comment by smnorris** [comment]
I haven't bothered to actually delete the old function from the server but I've switched my scripts to use the new func. Probably a good idea to switch.

**Comment by sebdalgarno** [comment]
ok great thanks will switch
