### ISSUE TITLE
check valid collectionid

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/fwapgr#31]
from list of collections in test-metadata

**Comment by sebdalgarno** [comment]
should make vector of collectionids internal data?

**Comment by sebdalgarno** [comment]
is it possible to make daily updates of internal data via Actions? That way we could ensure collection_id lookup is always up-to-date

**Comment by joethorley** [comment]
Yes this is totally possible - do you want to work on together on Friday or the weekend?

**Comment by sebdalgarno** [comment]
very cool. Yes let's work on it Friday. We could save the entire table from equivalent of `fwa_meta_collections()` daily..this would also speed up running `fwa_meta_collections()` as wouldn't need to query API

**Comment by joethorley** [comment]
Thinking about it some more I'm not sure we want to make it internal data or automatically update. Currently the test tests if something gets dropped but is fine with something being added. This is good behaviour - if we update it automatically then it won't give an error if something is dropped but we want to know about this. Also updating the version on GitHub won't update the table for users until they reinstall from GitHub which is not that often.

**Comment by sebdalgarno** [comment]
good points. Since this package is for power users I dont think we need to inform user if collection_id is incorrect (the API call will still fail)
