### ISSUE TITLE
functions return data in EPSG:3005 (4326 is expected)

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/fwapgr#62]
e.g. https://features.hillcrestgeo.ca/fwa/functions/postgisftw.fwa_watershedhex/items.html?blue_line_key=356308001&downstream_route_measure=10000&limit=10

are coordinates in correct CRS?

**Comment by smnorris** [comment]
It does seem to be a CRS issue, but the function has not been changed. Other functions seem to have the same issue, and all seems to be fine when working directly with the db.
First thought is this could maybe be related to upgrading pg_featurserv to support CQL on May 4.  Did you use the service successfully between then and last week?

**Comment by sebdalgarno** [comment]
unfortunately I'm not sure whether these functions worked as expected between May 4th and last week

**Comment by smnorris** [comment]
ok, no worries. I'm currently upgrading the db to pg14 - once that is done I'll look more closely into the functions

**Comment by smnorris** [comment]
I've filed an issue upstream. The function code has not changed, testing locally with pgfs 1.3 gives the same result, and testing locally with pgfs v1.2 works fine. Unless I've missed a required config setting or function change with 1.3 it appears to be a bug.

Let me know if you need this sooner rather than later and I can revert back to 1.2

**Comment by joethorley** [comment]
if we look at the coordinates of the returned locations is it obvious what CRS is being used?

**Comment by joethorley** [comment]
@sebdalgarno  are we able to reproject conditional on the CRS to have code that is robust to the projection provided?

**Comment by smnorris** [comment]
This doesn't seem to make any difference:
https://features.hillcrestgeo.ca/fwa/functions/postgisftw.fwa_watershedhex/items.json?blue_line_key=356308001&downstream_route_measure=10000&limit=10&crs=4326

**Comment by smnorris** [comment]
I've tweaked the functions to specifically return WGS84.

https://features.hillcrestgeo.ca/fwa/functions/postgisftw.fwa_locatealonginterval/items.html?blue_line_key=359572348&start_measure=1597489&interval_length=700&end_measure=1706733&limit=1000

**Comment by smnorris** [comment]
pgfs issue is fixed. I've installed the latest and reverted the db functions back to as they were.
All seems to work fine:
https://features.hillcrestgeo.ca/fwa/functions/postgisftw.fwa_locatealonginterval/items.html?blue_line_key=359572348&start_measure=1597510&interval_length=700&end_measure=1706733&limit=1000

**Comment by sebdalgarno** [comment]
thanks @smnorris tests are now passing and all looks like back to functioning normally
