### ISSUE TITLE
watershed_groups_subdivided not present in api

### ISSUE THREAD

**Issue by smnorris** [poissonconsulting/fwapgr#63]
I've removed `whse_basemapping.fwa_watershed_groups_subdivided` from the database so the collection is no longer present
https://github.com/poissonconsulting/fwapgr/search?q=subdivided

The table is still useful for some workflows but doesn't seem necessary to serve up, let me know if it is useful.

**Comment by sebdalgarno** [comment]
@joethorley Ive updated our test snapshots to no longer expect whse_basemapping.fwa_watershed_groups_subdivided in collection properties and metadata. I'll close this as I don't see it as a very necessary part of our workflows
