### ISSUE TITLE
API testing

### ISSUE THREAD

**Issue by smnorris** [poissonconsulting/fwapgr#66]
- bypass cache with `/?nocache=true`
- check that features returned are in expected CRS

**Comment by sebdalgarno** [comment]
@smnorris is there a way for me to see what is in the cache? 
I have added an argument to implement nocache=true but am having trouble determining whether it is actually working or not.

**Comment by smnorris** [comment]
Maybe? 
I can try and familiarize myself more with the cache system. 
https://www.nginx.com/resources/videos/best-practices-for-caching/

**Comment by joethorley** [comment]
Yes we now have nocache true for all testing and also check CRS.
