### ISSUE TITLE
hydro shed function API error

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/fwapgr#69]
no longer able to read data from hydroshed function given the following parameter values:
- x = -124.6
- y = 54.8

```
https://features.hillcrestgeo.ca/fwa/functions/postgisftw.hydroshed/items.json?x=-124.6&y=54.8&srid=4326
```

**Comment by smnorris** [comment]
This was a problem with the data load. Fixed now.

**Comment by smnorris** [comment]
The data load is fixed but there is a separate issue in that the function is not compatible with `pg_featureserv`.
https://github.com/smnorris/fwapg/issues/108

Changing the function to make it visible to pgfs will break `FWA_WatershedAtMeasure` (although it is an easy fix). But is the FWA_Hydroshed function valuable and useful, does it need to be available via the API?

**Comment by sebdalgarno** [comment]
Joe is currently on vacation but perhaps he can weigh in when he gets back next week on how valuable the hydroshed function is

**Comment by smnorris** [comment]
I'm speculating that it may have been a test function or older function that did not make it into version control but was still in the database.  I don't see any reference to a function named `hydroshed` in version control, just current `FWA_hydroshed`.

**Comment by joethorley** [comment]
I think this is a useful function

**Comment by sebdalgarno** [comment]
sounds good!

**Comment by smnorris** [comment]
function `hydroshed` is available again and the actions workflow is no longer bailing at the function.

**Comment by smnorris** [comment]
Not sure what this is referring to:
```
Backtrace:
    ▆
 1. └─fwapgr:::expect_snapshot_data(collections["collection_id"], "collections") at test-collections.R:9:2
 2.   └─testthat::expect_snapshot_file(path, paste0(name, ".csv"))
── Failure (test-meta-collections.R:13:3): fwa_meta_collections collection_id values haven't changed ──
Snapshot of `path` to 'meta-collections/collections.csv' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/meta-collections/collections.new.csv' to local test directory
* Run `testthat::snapshot_review('meta-collections/')` to review changes
Error: Error: R CMD check found ERRORs
```

**Comment by joethorley** [comment]
We save copies of the results of queries to see how they have changed. This might be unrelated to hydro sheds or may be a a minor difference. We'll look into it - interestingly the test passed on the windows OS.

**Comment by smnorris** [comment]
There is a very slight change in results (area sums) from the hydrosheds function. 
The data is unchanged so it must be a software upgrade quirk.

**Comment by joethorley** [comment]
Yes hydroshed function is all hunky dory.

**Comment by joethorley** [comment]
@smnorris - I can see the [usgs.wbdhu12](https://features.hillcrestgeo.ca/fwa/collections/usgs.wbdhu12.html) collection but not a huc12 function. Is this something you are going to export?

**Comment by smnorris** [comment]
Sure, easy to do if it is useful.

**Comment by joethorley** [comment]
I'm not sure - can you point me at some information on what it would do?

**Comment by smnorris** [comment]
It returns aggregated USGS HUC12 level watershed boundary upstream of the watershed corresponding to the input HUC12 id, including the watershed with the provided id. `FWA_WatershedAtMeasure` uses it internally to include USA watersheds for cross-border streams.

1.  If making this a public function, a more descriptive name would be useful, probably `huc12_upstream`

2. If you are working just USGS data and not attempting to combine with FWA data, using an American API might be better. I've used the EPA services below - the documentation links are dead but it seems the service is still up

Services:
- https://ofmpub.epa.gov/waters10/NavigationDelineation.Service
- http://ofmpub.epa.gov/waters10/PointIndexing.Service?

Documentation (hopefully available somewhere else?):
- https://www.epa.gov/waterdata/point-indexing-service
- https://www.epa.gov/waterdata/navigation-delineation-service
- https://www.epa.gov/waterdata/waters-web-services

**Comment by joethorley** [comment]
Thanks Simon - I don't think its worth it at this point
